// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"

	"github.com/context-dot-dev/context-dev-cli/internal/apiquery"
	"github.com/context-dot-dev/context-dev-cli/internal/requestflag"
	"github.com/context-dot-dev/context-go-sdk"
	"github.com/context-dot-dev/context-go-sdk/option"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var monitorsCreate = requestflag.WithInnerFlags(cli.Command{
	Name:    "create",
	Usage:   "Creates a monitor. The request body is a union of the supported target/change\ndetection combinations. The monitor runs immediately after creation to create\nits initial baseline.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[map[string]any]{
			Name:     "change-detection",
			Usage:    "Detect exact changes. For page targets, this means visible text diffs. For sitemap targets, this means URL additions and removals.",
			Required: true,
			BodyPath: "change_detection",
		},
		&requestflag.Flag[string]{
			Name:     "name",
			Required: true,
			BodyPath: "name",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "schedule",
			Usage:    "Run the monitor on a fixed interval defined by a frequency and a unit, e.g. every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.",
			Required: true,
			BodyPath: "schedule",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "target",
			Required: true,
			BodyPath: "target",
		},
		&requestflag.Flag[[]string]{
			Name:     "tag",
			Usage:    "User-defined tags for grouping and filtering monitors and their changes.",
			BodyPath: "tags",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "webhook",
			BodyPath: "webhook",
		},
	},
	Action:          handleMonitorsCreate,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"change-detection": {
		&requestflag.InnerFlag[string]{
			Name:       "change-detection.type",
			Usage:      `Allowed values: "exact".`,
			InnerField: "type",
		},
	},
	"schedule": {
		&requestflag.InnerFlag[int64]{
			Name:       "schedule.frequency",
			Usage:      "Number of units between runs. The resulting interval (frequency × unit) must be at least 10 minutes and at most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is days).",
			InnerField: "frequency",
		},
		&requestflag.InnerFlag[string]{
			Name:       "schedule.type",
			Usage:      `Allowed values: "interval".`,
			InnerField: "type",
		},
		&requestflag.InnerFlag[string]{
			Name:       "schedule.unit",
			Usage:      `Allowed values: "minutes", "hours", "days".`,
			InnerField: "unit",
		},
	},
	"target": {
		&requestflag.InnerFlag[string]{
			Name:       "target.type",
			Usage:      `Allowed values: "page".`,
			InnerField: "type",
		},
		&requestflag.InnerFlag[string]{
			Name:       "target.url",
			InnerField: "url",
		},
		&requestflag.InnerFlag[bool]{
			Name:       "target.normalize-whitespace",
			Usage:      "Normalize whitespace before comparing or analyzing text.",
			InnerField: "normalize_whitespace",
		},
	},
	"webhook": {
		&requestflag.InnerFlag[string]{
			Name:       "webhook.url",
			Usage:      "Webhook URL called when a change is detected.",
			InnerField: "url",
		},
		&requestflag.InnerFlag[string]{
			Name:       "webhook.secret",
			Usage:      "Signing secret used to verify webhook authenticity. Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header, where the HMAC is SHA-256 over `\"{t}.{rawRequestBody}\"` keyed by this secret. Recompute it with a constant-time compare and reject stale timestamps to prevent replay. Generated by the API; cannot be set by clients.",
			InnerField: "secret",
		},
	},
})

var monitorsRetrieve = cli.Command{
	Name:    "retrieve",
	Usage:   "Get a monitor",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			Required:  true,
			PathParam: "monitor_id",
		},
	},
	Action:          handleMonitorsRetrieve,
	HideHelpCommand: true,
}

var monitorsUpdate = requestflag.WithInnerFlags(cli.Command{
	Name:    "update",
	Usage:   "Updates a monitor. If `target` or `change_detection` changes, the monitor\ncreates a new baseline. Unsupported target/change detection combinations are\nrejected.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			Required:  true,
			PathParam: "monitor_id",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "change-detection",
			Usage:    "Discriminated union describing how changes are detected.",
			BodyPath: "change_detection",
		},
		&requestflag.Flag[string]{
			Name:     "name",
			BodyPath: "name",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "schedule",
			Usage:    "Run the monitor on a fixed interval defined by a frequency and a unit, e.g. every 6 hours or every 2 days. The total interval (frequency × unit) must be between 10 minutes and 1 year.",
			BodyPath: "schedule",
		},
		&requestflag.Flag[string]{
			Name:     "status",
			Usage:    `Allowed values: "active", "paused".`,
			BodyPath: "status",
		},
		&requestflag.Flag[[]string]{
			Name:     "tag",
			Usage:    "User-defined tags for grouping and filtering monitors and their changes.",
			BodyPath: "tags",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "target",
			Usage:    "Discriminated union describing what the monitor watches.",
			BodyPath: "target",
		},
		&requestflag.Flag[map[string]any]{
			Name:     "webhook",
			Usage:    "Set to null to remove the webhook.",
			BodyPath: "webhook",
		},
	},
	Action:          handleMonitorsUpdate,
	HideHelpCommand: true,
}, map[string][]requestflag.HasOuterFlag{
	"schedule": {
		&requestflag.InnerFlag[int64]{
			Name:       "schedule.frequency",
			Usage:      "Number of units between runs. The resulting interval (frequency × unit) must be at least 10 minutes and at most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is days).",
			InnerField: "frequency",
		},
		&requestflag.InnerFlag[string]{
			Name:       "schedule.type",
			Usage:      `Allowed values: "interval".`,
			InnerField: "type",
		},
		&requestflag.InnerFlag[string]{
			Name:       "schedule.unit",
			Usage:      `Allowed values: "minutes", "hours", "days".`,
			InnerField: "unit",
		},
	},
	"webhook": {
		&requestflag.InnerFlag[string]{
			Name:       "webhook.url",
			Usage:      "Webhook URL called when a change is detected.",
			InnerField: "url",
		},
		&requestflag.InnerFlag[string]{
			Name:       "webhook.secret",
			Usage:      "Signing secret used to verify webhook authenticity. Each delivery includes an `X-Context-Signature: t=<unix>,v1=<hmac>` header, where the HMAC is SHA-256 over `\"{t}.{rawRequestBody}\"` keyed by this secret. Recompute it with a constant-time compare and reject stale timestamps to prevent replay. Generated by the API; cannot be set by clients.",
			InnerField: "secret",
		},
	},
})

var monitorsList = cli.Command{
	Name:    "list",
	Usage:   "List monitors",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "change-detection-type",
			Usage:     `Allowed values: "exact", "semantic".`,
			QueryPath: "change_detection_type",
		},
		&requestflag.Flag[string]{
			Name:      "cursor",
			QueryPath: "cursor",
		},
		&requestflag.Flag[int64]{
			Name:      "limit",
			Default:   25,
			QueryPath: "limit",
		},
		&requestflag.Flag[string]{
			Name:      "status",
			Usage:     `Allowed values: "active", "paused", "failed".`,
			QueryPath: "status",
		},
		&requestflag.Flag[string]{
			Name:      "tag",
			Usage:     "Filter to items that have this tag.",
			QueryPath: "tag",
		},
		&requestflag.Flag[string]{
			Name:      "target-type",
			Usage:     `Allowed values: "page", "sitemap", "extract".`,
			QueryPath: "target_type",
		},
	},
	Action:          handleMonitorsList,
	HideHelpCommand: true,
}

var monitorsDelete = cli.Command{
	Name:    "delete",
	Usage:   "Delete a monitor",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			Required:  true,
			PathParam: "monitor_id",
		},
	},
	Action:          handleMonitorsDelete,
	HideHelpCommand: true,
}

var monitorsListAccountChanges = cli.Command{
	Name:    "list-account-changes",
	Usage:   "Returns an account-wide feed of detected changes across monitors.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "change-detection-type",
			Usage:     `Allowed values: "exact", "semantic".`,
			QueryPath: "change_detection_type",
		},
		&requestflag.Flag[string]{
			Name:      "cursor",
			QueryPath: "cursor",
		},
		&requestflag.Flag[int64]{
			Name:      "limit",
			Default:   25,
			QueryPath: "limit",
		},
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			QueryPath: "monitor_id",
		},
		&requestflag.Flag[any]{
			Name:      "since",
			QueryPath: "since",
		},
		&requestflag.Flag[string]{
			Name:      "tag",
			Usage:     "Filter to items that have this tag.",
			QueryPath: "tag",
		},
		&requestflag.Flag[string]{
			Name:      "target-type",
			Usage:     `Allowed values: "page", "sitemap", "extract".`,
			QueryPath: "target_type",
		},
		&requestflag.Flag[any]{
			Name:      "until",
			QueryPath: "until",
		},
	},
	Action:          handleMonitorsListAccountChanges,
	HideHelpCommand: true,
}

var monitorsListAccountRuns = cli.Command{
	Name:    "list-account-runs",
	Usage:   "Returns an account-wide feed of monitor runs across all monitors.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "cursor",
			QueryPath: "cursor",
		},
		&requestflag.Flag[int64]{
			Name:      "limit",
			Default:   25,
			QueryPath: "limit",
		},
		&requestflag.Flag[string]{
			Name:      "status",
			Usage:     `Allowed values: "queued", "running", "completed", "failed".`,
			QueryPath: "status",
		},
	},
	Action:          handleMonitorsListAccountRuns,
	HideHelpCommand: true,
}

var monitorsListChanges = cli.Command{
	Name:    "list-changes",
	Usage:   "List changes for a monitor",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			Required:  true,
			PathParam: "monitor_id",
		},
		&requestflag.Flag[string]{
			Name:      "cursor",
			QueryPath: "cursor",
		},
		&requestflag.Flag[int64]{
			Name:      "limit",
			Default:   25,
			QueryPath: "limit",
		},
		&requestflag.Flag[any]{
			Name:      "since",
			QueryPath: "since",
		},
		&requestflag.Flag[string]{
			Name:      "tag",
			Usage:     "Filter to items that have this tag.",
			QueryPath: "tag",
		},
		&requestflag.Flag[any]{
			Name:      "until",
			QueryPath: "until",
		},
	},
	Action:          handleMonitorsListChanges,
	HideHelpCommand: true,
}

var monitorsListRuns = cli.Command{
	Name:    "list-runs",
	Usage:   "List monitor runs",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			Required:  true,
			PathParam: "monitor_id",
		},
		&requestflag.Flag[string]{
			Name:      "cursor",
			QueryPath: "cursor",
		},
		&requestflag.Flag[int64]{
			Name:      "limit",
			Default:   25,
			QueryPath: "limit",
		},
		&requestflag.Flag[string]{
			Name:      "status",
			Usage:     `Allowed values: "queued", "running", "completed", "failed".`,
			QueryPath: "status",
		},
	},
	Action:          handleMonitorsListRuns,
	HideHelpCommand: true,
}

var monitorsRetrieveChange = cli.Command{
	Name:    "retrieve-change",
	Usage:   "Get a change",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "change-id",
			Required:  true,
			PathParam: "change_id",
		},
	},
	Action:          handleMonitorsRetrieveChange,
	HideHelpCommand: true,
}

var monitorsRun = cli.Command{
	Name:    "run",
	Usage:   "Triggers an immediate run of the monitor outside its normal schedule. The run is\nqueued and processed asynchronously.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "monitor-id",
			Required:  true,
			PathParam: "monitor_id",
		},
	},
	Action:          handleMonitorsRun,
	HideHelpCommand: true,
}

func handleMonitorsCreate(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorNewParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.New(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors create",
		Transform:      transform,
	})
}

func handleMonitorsRetrieve(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("monitor-id") && len(unusedArgs) > 0 {
		cmd.Set("monitor-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.Get(ctx, cmd.Value("monitor-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors retrieve",
		Transform:      transform,
	})
}

func handleMonitorsUpdate(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("monitor-id") && len(unusedArgs) > 0 {
		cmd.Set("monitor-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorUpdateParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.Update(
		ctx,
		cmd.Value("monitor-id").(string),
		params,
		options...,
	)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors update",
		Transform:      transform,
	})
}

func handleMonitorsList(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorListParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.List(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors list",
		Transform:      transform,
	})
}

func handleMonitorsDelete(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("monitor-id") && len(unusedArgs) > 0 {
		cmd.Set("monitor-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.Delete(ctx, cmd.Value("monitor-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors delete",
		Transform:      transform,
	})
}

func handleMonitorsListAccountChanges(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorListAccountChangesParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.ListAccountChanges(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors list-account-changes",
		Transform:      transform,
	})
}

func handleMonitorsListAccountRuns(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorListAccountRunsParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.ListAccountRuns(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors list-account-runs",
		Transform:      transform,
	})
}

func handleMonitorsListChanges(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("monitor-id") && len(unusedArgs) > 0 {
		cmd.Set("monitor-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorListChangesParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.ListChanges(
		ctx,
		cmd.Value("monitor-id").(string),
		params,
		options...,
	)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors list-changes",
		Transform:      transform,
	})
}

func handleMonitorsListRuns(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("monitor-id") && len(unusedArgs) > 0 {
		cmd.Set("monitor-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	params := contextdev.MonitorListRunsParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.ListRuns(
		ctx,
		cmd.Value("monitor-id").(string),
		params,
		options...,
	)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors list-runs",
		Transform:      transform,
	})
}

func handleMonitorsRetrieveChange(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("change-id") && len(unusedArgs) > 0 {
		cmd.Set("change-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.GetChange(ctx, cmd.Value("change-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors retrieve-change",
		Transform:      transform,
	})
}

func handleMonitorsRun(ctx context.Context, cmd *cli.Command) error {
	client := contextdev.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()
	if !cmd.IsSet("monitor-id") && len(unusedArgs) > 0 {
		cmd.Set("monitor-id", unusedArgs[0])
		unusedArgs = unusedArgs[1:]
	}
	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		EmptyBody,
		false,
	)
	if err != nil {
		return err
	}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Monitors.Run(ctx, cmd.Value("monitor-id").(string), options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "monitors run",
		Transform:      transform,
	})
}
